sudo: false
language: python
cache: pip
python:
- 3.6
install: skip
script: echo "Running tests ..."
stages:
- basic
- name: deploy
  if: branch = master
- notify
jobs:
  include:
  - stage: basic
    script: make lint
    name: Linting
  - script: make test
    name: Unit Tests
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: Nau4ZHJN5gy6RT5YeYY+p+Y53bOASr9nzODCCC7muvw4DCCyAyc6xYy9hBrKav90cCXBHkjPDVtYY25y8okIcF5qjF4eUKv1o8S4lnSgDh7SRTIj5C1QR+0zCArWCNS4oQoCCVV20ene5xFMEr4vyY4K5H+HlgzOUGxdD57htjRD8nyzHZvv6+WZlACBtiK1TZQpVj+qfvFS5OCpCxz8pWEIfqvt7/vbySAC9e4XhyvOtltfoFK19zQpZIwnXd4E4Z48mZIdSC2c/uNxugPKb5lvpfss/H3BARQCF/nJgtE2nAY59GW2R9LA7AAMJNf6tZNNBQQ+nest6S7hMInsoU+xrL7gixtoqeAy4Ojcw2Wyn2ohRj3hjZS9V0LE7Vb+M1CFARaSekwqD2kTWr46G4mMfzhmTM6pH5SPd2CMmzGeqkbsdCDednOds9K9qdyP98W20UPIrcvx8IEJZFk0GJJoAuVS+iSznVLMqIOmX8zyUwIe8QMMj6Kn9uG4yaM/U9rdGf4dL3hAoffbSNToDxfiIIj2aR0nd40P6AmDFJFG4sV7HY+aaVh1eRQkfgzFAGilabqZlTiBswyAx4+G2rAA7vZgMEGjbMlZ+BfBw9gs2jERlSCTCi5wwdU95swkTPUp9vnyiePRr4Q2sCT0efr/gehNSADUbmoK1JooWeM=
      app: nisb-events
  - stage: notify
    notifications:
      email: mridul.kepler@gmail.com

branches:
  only: 
    - master
